/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Product = IDL.Record({
  'sku' : IDL.Text,
  'defaultRate' : IDL.Opt(IDL.Nat),
  'stockQty' : IDL.Nat,
  'storeId' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'hsnCode' : IDL.Text,
  'gstRate' : IDL.Nat,
  'price' : IDL.Nat,
});
export const LineItem = IDL.Record({
  'qty' : IDL.Nat,
  'rate' : IDL.Nat,
  'lineTotal' : IDL.Nat,
  'sgstAmt' : IDL.Nat,
  'hsnCode' : IDL.Text,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'gstRate' : IDL.Nat,
  'igstAmt' : IDL.Nat,
  'cgstAmt' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'customerName' : IDL.Text,
  'customerGstin' : IDL.Text,
  'lineItems' : IDL.Vec(LineItem),
  'date' : Time,
  'storeId' : IDL.Principal,
  'createdAt' : Time,
  'customerMobile' : IDL.Text,
  'totalCgst' : IDL.Nat,
  'totalIgst' : IDL.Nat,
  'isIgst' : IDL.Bool,
  'totalSgst' : IDL.Nat,
  'grandTotal' : IDL.Nat,
  'invoiceNumber' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const AdminStoreView = IDL.Record({
  'fssai' : IDL.Text,
  'credits' : IDL.Nat,
  'owner' : IDL.Principal,
  'state' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'storeName' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StoreProfile = IDL.Record({
  'fssai' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'state' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const StoreSummary = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalCgst' : IDL.Nat,
  'totalIgst' : IDL.Nat,
  'totalSgst' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'storeProfile' : StoreProfile,
  'totalInvoices' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCreditsAdmin' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
      ],
      [Product],
      [],
    ),
  'createInvoice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(LineItem)],
      [Invoice],
      [],
    ),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllStoresAdmin' : IDL.Func([], [IDL.Vec(AdminStoreView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getMyCredits' : IDL.Func([], [IDL.Nat], ['query']),
  'getNextInvoiceNumber' : IDL.Func([], [IDL.Nat], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStore' : IDL.Func([], [StoreProfile], ['query']),
  'getStoreSummary' : IDL.Func([], [StoreSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerStore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [StoreProfile],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInvoice' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(LineItem)],
      [Invoice],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
      ],
      [Product],
      [],
    ),
  'updateProductStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateStore' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [StoreProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Product = IDL.Record({
    'sku' : IDL.Text,
    'defaultRate' : IDL.Opt(IDL.Nat),
    'stockQty' : IDL.Nat,
    'storeId' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'hsnCode' : IDL.Text,
    'gstRate' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const LineItem = IDL.Record({
    'qty' : IDL.Nat,
    'rate' : IDL.Nat,
    'lineTotal' : IDL.Nat,
    'sgstAmt' : IDL.Nat,
    'hsnCode' : IDL.Text,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'gstRate' : IDL.Nat,
    'igstAmt' : IDL.Nat,
    'cgstAmt' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'customerName' : IDL.Text,
    'customerGstin' : IDL.Text,
    'lineItems' : IDL.Vec(LineItem),
    'date' : Time,
    'storeId' : IDL.Principal,
    'createdAt' : Time,
    'customerMobile' : IDL.Text,
    'totalCgst' : IDL.Nat,
    'totalIgst' : IDL.Nat,
    'isIgst' : IDL.Bool,
    'totalSgst' : IDL.Nat,
    'grandTotal' : IDL.Nat,
    'invoiceNumber' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const AdminStoreView = IDL.Record({
    'fssai' : IDL.Text,
    'credits' : IDL.Nat,
    'owner' : IDL.Principal,
    'state' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'storeName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StoreProfile = IDL.Record({
    'fssai' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'state' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StoreSummary = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalCgst' : IDL.Nat,
    'totalIgst' : IDL.Nat,
    'totalSgst' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'storeProfile' : StoreProfile,
    'totalInvoices' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCreditsAdmin' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
        ],
        [Product],
        [],
      ),
    'createInvoice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(LineItem)],
        [Invoice],
        [],
      ),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllStoresAdmin' : IDL.Func([], [IDL.Vec(AdminStoreView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getMyCredits' : IDL.Func([], [IDL.Nat], ['query']),
    'getNextInvoiceNumber' : IDL.Func([], [IDL.Nat], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStore' : IDL.Func([], [StoreProfile], ['query']),
    'getStoreSummary' : IDL.Func([], [StoreSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerStore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [StoreProfile],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInvoice' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(LineItem)],
        [Invoice],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
        ],
        [Product],
        [],
      ),
    'updateProductStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateStore' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [StoreProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };