/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStoreView {
  'credits' : bigint,
  'owner' : Principal,
  'storeName' : string,
}
export interface Invoice {
  'customerName' : string,
  'customerGstin' : string,
  'lineItems' : Array<LineItem>,
  'date' : Time,
  'storeId' : Principal,
  'createdAt' : Time,
  'totalCgst' : bigint,
  'totalIgst' : bigint,
  'isIgst' : boolean,
  'totalSgst' : bigint,
  'grandTotal' : bigint,
  'invoiceNumber' : bigint,
  'subtotal' : bigint,
}
export interface LineItem {
  'qty' : bigint,
  'rate' : bigint,
  'lineTotal' : bigint,
  'sgstAmt' : bigint,
  'hsnCode' : string,
  'productId' : string,
  'productName' : string,
  'gstRate' : bigint,
  'igstAmt' : bigint,
  'cgstAmt' : bigint,
}
export interface Product {
  'sku' : string,
  'stockQty' : bigint,
  'storeId' : Principal,
  'name' : string,
  'createdAt' : Time,
  'hsnCode' : string,
  'gstRate' : bigint,
  'price' : bigint,
}
export interface StoreProfile {
  'fssai' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'state' : string,
  'gstin' : string,
  'address' : string,
  'phone' : string,
}
export interface StoreSummary {
  'totalProducts' : bigint,
  'totalCgst' : bigint,
  'totalIgst' : bigint,
  'totalSgst' : bigint,
  'totalSales' : bigint,
  'storeProfile' : StoreProfile,
  'totalInvoices' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCreditsAdmin' : ActorMethod<[Principal, bigint], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, bigint, bigint, bigint],
    Product
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createInvoice' : ActorMethod<
    [string, string, boolean, Array<LineItem>],
    Invoice
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllStoresAdmin' : ActorMethod<[], Array<AdminStoreView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getMyCredits' : ActorMethod<[], bigint>,
  'getNextInvoiceNumber' : ActorMethod<[], bigint>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getStore' : ActorMethod<[], StoreProfile>,
  'getStoreSummary' : ActorMethod<[], StoreSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerStore' : ActorMethod<
    [string, string, string, string, string, string],
    StoreProfile
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, bigint, bigint],
    Product
  >,
  'updateProductStock' : ActorMethod<[string, bigint], undefined>,
  'updateStore' : ActorMethod<
    [string, string, string, string, string, string],
    StoreProfile
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];